export const CRYPTOCURRENCIES: { name: string; ticker: string; }[] = [
    { name: 'Bitcoin', ticker: 'BTC' },
    { name: 'Ethereum', ticker: 'ETH' },
    { name: 'Tether', ticker: 'USDT' },
    { name: 'BNB', ticker: 'BNB' },
    { name: 'Solana', ticker: 'SOL' },
    { name: 'USD Coin', ticker: 'USDC' },
    { name: 'XRP', ticker: 'XRP' },
    { name: 'Dogecoin', ticker: 'DOGE' },
    { name: 'Toncoin', ticker: 'TON' },
    { name: 'Cardano', ticker: 'ADA' },
    { name: 'Shiba Inu', ticker: 'SHIB' },
    { name: 'Avalanche', ticker: 'AVAX' },
    { name: 'TRON', ticker: 'TRX' },
    { name: 'Polkadot', ticker: 'DOT' },
    { name: 'Bitcoin Cash', ticker: 'BCH' },
    { name: 'Chainlink', ticker: 'LINK' },
    { name: 'Polygon', ticker: 'MATIC' },
    { name: 'Near Protocol', ticker: 'NEAR' },
    { name: 'Litecoin', ticker: 'LTC' },
    { name: 'Uniswap', ticker: 'UNI' },
    { name: 'Pepe', ticker: 'PEPE' },
    { name: 'Kaspa', ticker: 'KAS' },
    { name: 'Ethereum Classic', ticker: 'ETC' },
    { name: 'Dai', ticker: 'DAI' },
    { name: 'Aptos', ticker: 'APT' },
    { name: 'Monero', ticker: 'XMR' },
    { name: 'Render', ticker: 'RNDR' },
    { name: 'Hedera', ticker: 'HBAR' },
    { name: 'Stellar', ticker: 'XLM' },
    { name: 'Cosmos', ticker: 'ATOM' },
    { name: 'Arbitrum', ticker: 'ARB' },
    { name: 'OKB', ticker: 'OKB' },
    { name: 'Filecoin', ticker: 'FIL' },
    { name: 'Immutable', ticker: 'IMX' },
    { name: 'Cronos', ticker: 'CRO' },
    { name: 'VeChain', ticker: 'VET' },
    { name: 'Injective', ticker: 'INJ' },
    { name: 'Sui', ticker: 'SUI' },
    { name: 'The Graph', ticker: 'GRT' },
    { name: 'Optimism', ticker: 'OP' },
    { name: 'Bittensor', ticker: 'TAO' },
    { name: 'Arweave', ticker: 'AR' },
    { name: 'Celestia', ticker: 'TIA' },
    { name: 'Fantom', ticker: 'FTM' },
    { name: 'Theta Network', ticker: 'THETA' },
    { name: 'Lido DAO', ticker: 'LDO' },
    { name: 'Aave', ticker: 'AAVE' },
    { name: 'Algorand', ticker: 'ALGO' },
    { name: 'Maker', ticker: 'MKR' },
    { name: 'Sei', ticker: 'SEI' },
    { name: 'dogwifhat', ticker: 'WIF' }
];
